export const ARTICLES = [
  {
    id: "what-is-adhd-masking",
    title: "What is ADHD masking?",
    subtitle: "Why so many adults with ADHD go undiagnosed — and the hidden cost of appearing fine.",
    readTime: "5 min read",
    description: "Masking is when someone with ADHD hides or compensates for their symptoms. Learn why it leads to missed diagnoses and how ADHD Mirror accounts for it.",
    content: [
      { type: "intro", text: "Masking — also called 'camouflaging' — is the conscious or unconscious process of hiding ADHD symptoms in order to fit in, meet expectations, or avoid judgment. For many adults, it's so deeply ingrained that they don't realise they're doing it." },
      { type: "heading", text: "What does masking look like?" },
      { type: "paragraph", text: "Masking looks different for different people. It might mean memorising social scripts so that conversations feel easier. It might mean arriving early to every meeting to compensate for time blindness. It might mean building elaborate systems of alarms, lists, and rituals just to do what others seem to manage effortlessly." },
      { type: "paragraph", text: "From the outside, a person who masks effectively looks organised, capable, and on top of things. From the inside, they're exhausted — running two versions of themselves at once: the one the world sees, and the one they know is barely holding it together." },
      { type: "pullquote", text: "Masking is a performance that costs far more energy than the audience ever sees." },
      { type: "heading", text: "Why masking leads to missed diagnoses" },
      { type: "paragraph", text: "Traditional ADHD screening tools were largely developed on young boys with obvious hyperactive symptoms. Adults — and especially women — who have spent years compensating for their difficulties often don't 'look' like someone with ADHD." },
      { type: "paragraph", text: "The problem is that masking doesn't make the underlying difficulties go away. It just hides them — from others, and from standard assessments. A person can score below the threshold on a checklist not because their symptoms are mild, but because they've spent thirty years becoming very good at compensating for them." },
      { type: "heading", text: "The cost of long-term masking" },
      { type: "paragraph", text: "Research has consistently linked high masking with significantly worse mental health outcomes — including higher rates of anxiety, depression, burnout, and autistic or ADHD burnout specifically." },
      { type: "paragraph", text: "Many people who are diagnosed in adulthood describe a moment of grief alongside the relief — grief for the version of themselves who spent decades working twice as hard just to keep pace, and who was never told why." },
      { type: "heading", text: "How ADHD Mirror accounts for masking" },
      { type: "paragraph", text: "Most ADHD screening tools ignore masking entirely. ADHD Mirror includes a dedicated masking section and applies your masking score as an upward modifier to your overall result — recognising that high compensatory coping can suppress raw symptom scores and underestimate the real picture." },
    ],
  },
  {
    id: "adhd-in-adults-late-diagnosis",
    title: "ADHD in adults: why so many people are diagnosed late",
    subtitle: "The gap between childhood diagnosis and adult reality — and what makes adult ADHD so easy to miss.",
    readTime: "6 min read",
    description: "Millions of adults are living with undiagnosed ADHD. Learn why it gets missed, what it looks like in adults, and whether a late diagnosis is worth pursuing.",
    content: [
      { type: "intro", text: "ADHD has long been thought of as a childhood condition — something hyperactive boys grow out of, or that gets caught in school. The reality is that millions of adults are living with undiagnosed ADHD." },
      { type: "heading", text: "Why adult ADHD goes unrecognised" },
      { type: "paragraph", text: "There are several reasons why ADHD is frequently missed in adults. The first is the stereotype: ADHD is still widely associated with small boys who can't sit still. Adults — particularly women, and particularly those with the inattentive presentation — simply don't match that image." },
      { type: "paragraph", text: "The second is masking. By adulthood, many people with ADHD have developed elaborate compensatory strategies. They appear to manage — even to thrive — while privately exerting a level of effort that is fundamentally unsustainable." },
      { type: "pullquote", text: "Many adults describe looking back at a lifetime of underperformance, missed potential, and chronic self-blame — and realising, for the first time, that there was a reason." },
      { type: "heading", text: "The gender gap in diagnosis" },
      { type: "paragraph", text: "Boys are roughly three times more likely to be diagnosed with ADHD in childhood. Women with ADHD tend to show more internalised symptoms: anxiety, perfectionism, people-pleasing, and relentless self-criticism." },
      { type: "heading", text: "What does adult ADHD actually look like?" },
      { type: "paragraph", text: "In adults, ADHD often presents as chronic procrastination that feels like paralysis; an inability to start tasks despite genuinely wanting to; time blindness; intense emotional reactivity; and the peculiar experience of being able to hyperfocus for hours on something engaging while being completely unable to attend to something you 'should' be doing." },
      { type: "heading", text: "Is a late diagnosis worth pursuing?" },
      { type: "paragraph", text: "For many people, yes. A formal diagnosis opens access to medication, psychological support, and a framework for understanding a lifetime of experiences that never quite made sense. The self-blame begins to lift when you understand the mechanism." },
    ],
  },
  {
    id: "adhd-vs-anxiety",
    title: "ADHD vs anxiety: how to tell the difference",
    subtitle: "Two conditions that look remarkably similar — and why they so often travel together.",
    readTime: "5 min read",
    description: "ADHD and anxiety share many symptoms and are frequently confused for each other. Learn the key differences and why they often co-occur in adults.",
    content: [
      { type: "intro", text: "ADHD and anxiety share so many surface-level symptoms that they're frequently confused for each other — or, just as commonly, one is treated while the other is left unaddressed." },
      { type: "heading", text: "The overlapping symptoms" },
      { type: "paragraph", text: "Both ADHD and anxiety can cause: difficulty concentrating, racing thoughts, restlessness, procrastination, avoidance of demanding tasks, sleep problems, and emotional dysregulation." },
      { type: "pullquote", text: "The question isn't just 'which one do I have?' — it's 'how are they interacting, and which came first?'" },
      { type: "heading", text: "Key differences to look for" },
      { type: "paragraph", text: "In anxiety, poor focus tends to be topic-specific: the mind is pulled towards worries. In ADHD, poor focus is more indiscriminate — it shifts based on interest, novelty, and urgency rather than emotional content." },
      { type: "paragraph", text: "Timing is also informative. ADHD symptoms are typically lifelong. Anxiety can develop at any point and is often linked to specific circumstances. If your concentration has always been poor, ADHD is more likely." },
      { type: "heading", text: "When they co-occur" },
      { type: "paragraph", text: "Approximately 50% of adults with ADHD also meet criteria for an anxiety disorder. ADHD makes life harder, and the missed deadlines, the constant sense of underperforming create fertile ground for anxiety to develop." },
    ],
  },
  {
    id: "what-does-adhd-assessment-involve",
    title: "What does an ADHD assessment actually involve?",
    subtitle: "What to expect before, during, and after a formal ADHD evaluation — and how to prepare.",
    readTime: "5 min read",
    description: "A practical guide to what a formal ADHD assessment involves in the UK — who carries it out, what happens during it, and what to do if you're diagnosed.",
    content: [
      { type: "intro", text: "For many people, the idea of a formal ADHD assessment is both appealing and intimidating. Here's a practical overview of what to expect." },
      { type: "heading", text: "Who carries out an ADHD assessment?" },
      { type: "paragraph", text: "In the UK, ADHD can be formally diagnosed by a psychiatrist or clinical psychologist. You can access this via the NHS (through a GP referral) or privately (expect to pay £500–£1,500)." },
      { type: "paragraph", text: "The Right to Choose pathway allows UK patients to choose an alternative provider to their local NHS service — this can significantly reduce waiting times." },
      { type: "heading", text: "What happens during the assessment?" },
      { type: "paragraph", text: "A comprehensive ADHD assessment typically includes a detailed clinical interview, exploration of your developmental history, standardised rating scales, and sometimes collateral information from a partner or family member." },
      { type: "pullquote", text: "The most useful thing you can bring to an assessment is specific examples — not just 'I'm disorganised', but the actual incidents that have cost you jobs, relationships, or years of self-blame." },
      { type: "heading", text: "What happens if you're diagnosed?" },
      { type: "paragraph", text: "A positive diagnosis opens access to medication, psychological interventions, and formal workplace or educational accommodations. Many people describe the post-diagnosis period as a mixture of relief and grief — both are entirely valid." },
    ],
  },
  {
    id: "adhd-in-women",
    title: "ADHD in women: why it looks different and gets missed",
    subtitle: "How ADHD presents differently in women — and the systemic reasons so many go undiagnosed until adulthood.",
    readTime: "6 min read",
    description: "ADHD in women is one of the most underdiagnosed conditions in mental health. Learn how it presents differently and why so many women aren't diagnosed until adulthood.",
    content: [
      { type: "intro", text: "ADHD in women is one of the most underrecognised and underdiagnosed conditions in mental health — not because it's rare, but because the clinical picture looks different." },
      { type: "heading", text: "The research gap" },
      { type: "paragraph", text: "Until the 1990s, nearly all ADHD research was conducted on young boys. The diagnostic criteria that emerged naturally reflected how ADHD presents in that population. Girls and women, whose ADHD more frequently presents as internalised distress, simply didn't match the template." },
      { type: "pullquote", text: "Women are often told they can't have ADHD because they were good at school. What's missed is how much harder they were working to get there." },
      { type: "heading", text: "How ADHD typically presents in women" },
      { type: "paragraph", text: "Women with ADHD more commonly show the inattentive presentation — internal restlessness, difficulty sustaining attention, and a tendency to internalise failure as personal inadequacy." },
      { type: "paragraph", text: "Common experiences include: chronic disorganisation masked by heroic effort; perfectionism as a coping mechanism; emotional intensity and rejection sensitivity; and a deep, often lifelong sense of being 'too much' or 'not enough'." },
      { type: "heading", text: "What to do if you suspect ADHD" },
      { type: "paragraph", text: "When you approach your GP, be specific about the ways your difficulties have impacted your functioning — not how you've coped with them, but what it has cost you. The compensation is often invisible. Make it visible." },
    ],
  },
];
