export const ARTICLES = [
  {
    id: "what-is-adhd-masking",
    title: "What is ADHD masking?",
    subtitle: "Why so many adults with ADHD go undiagnosed — and the hidden cost of appearing fine.",
    readTime: "5 min read",
    description: "Masking is when someone with ADHD hides or compensates for their symptoms. Learn why it leads to missed diagnoses and how ADHD Mirror accounts for it.",
    content: [
      { type: "intro", text: "Masking — also called 'camouflaging' — is the conscious or unconscious process of hiding ADHD symptoms in order to fit in, meet expectations, or avoid judgment. For many adults, it's so deeply ingrained that they don't realise they're doing it." },
      { type: "heading", text: "What does masking look like?" },
      { type: "paragraph", text: "Masking looks different for different people. It might mean memorising social scripts so that conversations feel easier. It might mean arriving early to every meeting to compensate for time blindness. It might mean building elaborate systems of alarms, lists, and rituals just to do what others seem to manage effortlessly." },
      { type: "paragraph", text: "From the outside, a person who masks effectively looks organised, capable, and on top of things. From the inside, they're exhausted — running two versions of themselves at once: the one the world sees, and the one they know is barely holding it together." },
      { type: "pullquote", text: "Masking is a performance that costs far more energy than the audience ever sees." },
      { type: "heading", text: "Why masking leads to missed diagnoses" },
      { type: "paragraph", text: "Traditional ADHD screening tools were largely developed on young boys with obvious hyperactive symptoms. Adults — and especially women — who have spent years compensating for their difficulties often don't 'look' like someone with ADHD." },
      { type: "paragraph", text: "The problem is that masking doesn't make the underlying difficulties go away. It just hides them — from others, and from standard assessments. A person can score below the threshold on a checklist not because their symptoms are mild, but because they've spent thirty years becoming very good at compensating for them." },
      { type: "heading", text: "The cost of long-term masking" },
      { type: "paragraph", text: "Research has consistently linked high masking with significantly worse mental health outcomes — including higher rates of anxiety, depression, burnout, and autistic or ADHD burnout specifically." },
      { type: "paragraph", text: "Many people who are diagnosed in adulthood describe a moment of grief alongside the relief — grief for the version of themselves who spent decades working twice as hard just to keep pace, and who was never told why." },
      { type: "heading", text: "How ADHD Mirror accounts for masking" },
      { type: "paragraph", text: "Most ADHD screening tools ignore masking entirely. ADHD Mirror includes a dedicated masking section and applies your masking score as an upward modifier to your overall result — recognising that high compensatory coping can suppress raw symptom scores and underestimate the real picture." },
    ],
  },
  {
    id: "adhd-in-adults-late-diagnosis",
    title: "ADHD in adults: why so many people are diagnosed late",
    subtitle: "The gap between childhood diagnosis and adult reality — and what makes adult ADHD so easy to miss.",
    readTime: "6 min read",
    description: "Millions of adults are living with undiagnosed ADHD. Learn why it gets missed, what it looks like in adults, and whether a late diagnosis is worth pursuing.",
    content: [
      { type: "intro", text: "ADHD has long been thought of as a childhood condition — something hyperactive boys grow out of, or that gets caught in school. The reality is that millions of adults are living with undiagnosed ADHD." },
      { type: "heading", text: "Why adult ADHD goes unrecognised" },
      { type: "paragraph", text: "There are several reasons why ADHD is frequently missed in adults. The first is the stereotype: ADHD is still widely associated with small boys who can't sit still. Adults — particularly women, and particularly those with the inattentive presentation — simply don't match that image." },
      { type: "paragraph", text: "The second is masking. By adulthood, many people with ADHD have developed elaborate compensatory strategies. They appear to manage — even to thrive — while privately exerting a level of effort that is fundamentally unsustainable." },
      { type: "pullquote", text: "Many adults describe looking back at a lifetime of underperformance, missed potential, and chronic self-blame — and realising, for the first time, that there was a reason." },
      { type: "heading", text: "The gender gap in diagnosis" },
      { type: "paragraph", text: "Boys are roughly three times more likely to be diagnosed with ADHD in childhood. Women with ADHD tend to show more internalised symptoms: anxiety, perfectionism, people-pleasing, and relentless self-criticism." },
      { type: "heading", text: "What does adult ADHD actually look like?" },
      { type: "paragraph", text: "In adults, ADHD often presents as chronic procrastination that feels like paralysis; an inability to start tasks despite genuinely wanting to; time blindness; intense emotional reactivity; and the peculiar experience of being able to hyperfocus for hours on something engaging while being completely unable to attend to something you 'should' be doing." },
      { type: "heading", text: "Is a late diagnosis worth pursuing?" },
      { type: "paragraph", text: "For many people, yes. A formal diagnosis opens access to medication, psychological support, and a framework for understanding a lifetime of experiences that never quite made sense. The self-blame begins to lift when you understand the mechanism." },
    ],
  },
  {
    id: "adhd-vs-anxiety",
    title: "ADHD vs anxiety: how to tell the difference",
    subtitle: "Two conditions that look remarkably similar — and why they so often travel together.",
    readTime: "5 min read",
    description: "ADHD and anxiety share many symptoms and are frequently confused for each other. Learn the key differences and why they often co-occur in adults.",
    content: [
      { type: "intro", text: "ADHD and anxiety share so many surface-level symptoms that they're frequently confused for each other — or, just as commonly, one is treated while the other is left unaddressed." },
      { type: "heading", text: "The overlapping symptoms" },
      { type: "paragraph", text: "Both ADHD and anxiety can cause: difficulty concentrating, racing thoughts, restlessness, procrastination, avoidance of demanding tasks, sleep problems, and emotional dysregulation." },
      { type: "pullquote", text: "The question isn't just 'which one do I have?' — it's 'how are they interacting, and which came first?'" },
      { type: "heading", text: "Key differences to look for" },
      { type: "paragraph", text: "In anxiety, poor focus tends to be topic-specific: the mind is pulled towards worries. In ADHD, poor focus is more indiscriminate — it shifts based on interest, novelty, and urgency rather than emotional content." },
      { type: "paragraph", text: "Timing is also informative. ADHD symptoms are typically lifelong. Anxiety can develop at any point and is often linked to specific circumstances. If your concentration has always been poor, ADHD is more likely." },
      { type: "heading", text: "When they co-occur" },
      { type: "paragraph", text: "Approximately 50% of adults with ADHD also meet criteria for an anxiety disorder. ADHD makes life harder, and the missed deadlines, the constant sense of underperforming create fertile ground for anxiety to develop." },
    ],
  },
  {
    id: "what-does-adhd-assessment-involve",
    title: "What does an ADHD assessment actually involve?",
    subtitle: "What to expect before, during, and after a formal ADHD evaluation — and how to prepare.",
    readTime: "5 min read",
    description: "A practical guide to what a formal ADHD assessment involves in the UK — who carries it out, what happens during it, and what to do if you're diagnosed.",
    content: [
      { type: "intro", text: "For many people, the idea of a formal ADHD assessment is both appealing and intimidating. Here's a practical overview of what to expect." },
      { type: "heading", text: "Who carries out an ADHD assessment?" },
      { type: "paragraph", text: "In the UK, ADHD can be formally diagnosed by a psychiatrist or clinical psychologist. You can access this via the NHS (through a GP referral) or privately (expect to pay £500–£1,500)." },
      { type: "paragraph", text: "The Right to Choose pathway allows UK patients to choose an alternative provider to their local NHS service — this can significantly reduce waiting times." },
      { type: "heading", text: "What happens during the assessment?" },
      { type: "paragraph", text: "A comprehensive ADHD assessment typically includes a detailed clinical interview, exploration of your developmental history, standardised rating scales, and sometimes collateral information from a partner or family member." },
      { type: "pullquote", text: "The most useful thing you can bring to an assessment is specific examples — not just 'I'm disorganised', but the actual incidents that have cost you jobs, relationships, or years of self-blame." },
      { type: "heading", text: "What happens if you're diagnosed?" },
      { type: "paragraph", text: "A positive diagnosis opens access to medication, psychological interventions, and formal workplace or educational accommodations. Many people describe the post-diagnosis period as a mixture of relief and grief — both are entirely valid." },
    ],
  },
  {
    id: "adhd-in-women",
    title: "ADHD in women: why it looks different and gets missed",
    subtitle: "How ADHD presents differently in women — and the systemic reasons so many go undiagnosed until adulthood.",
    readTime: "6 min read",
    description: "ADHD in women is one of the most underdiagnosed conditions in mental health. Learn how it presents differently and why so many women aren't diagnosed until adulthood.",
    content: [
      { type: "intro", text: "ADHD in women is one of the most underrecognised and underdiagnosed conditions in mental health — not because it's rare, but because the clinical picture looks different." },
      { type: "heading", text: "The research gap" },
      { type: "paragraph", text: "Until the 1990s, nearly all ADHD research was conducted on young boys. The diagnostic criteria that emerged naturally reflected how ADHD presents in that population. Girls and women, whose ADHD more frequently presents as internalised distress, simply didn't match the template." },
      { type: "pullquote", text: "Women are often told they can't have ADHD because they were good at school. What's missed is how much harder they were working to get there." },
      { type: "heading", text: "How ADHD typically presents in women" },
      { type: "paragraph", text: "Women with ADHD more commonly show the inattentive presentation — internal restlessness, difficulty sustaining attention, and a tendency to internalise failure as personal inadequacy." },
      { type: "paragraph", text: "Common experiences include: chronic disorganisation masked by heroic effort; perfectionism as a coping mechanism; emotional intensity and rejection sensitivity; and a deep, often lifelong sense of being 'too much' or 'not enough'." },
      { type: "heading", text: "What to do if you suspect ADHD" },
      { type: "paragraph", text: "When you approach your GP, be specific about the ways your difficulties have impacted your functioning — not how you've coped with them, but what it has cost you. The compensation is often invisible. Make it visible." },
    ],
  },
  {
    id: "how-to-talk-to-your-gp-about-adhd",
    title: "How to talk to your GP about ADHD",
    subtitle: "What to say, what to bring, and how to make sure you're taken seriously.",
    readTime: "5 min read",
    description: "Many adults with ADHD struggle to get their GP to take their concerns seriously. Here's how to prepare for the conversation and advocate effectively for a referral.",
    content: [
      { type: "intro", text: "For many adults who suspect they have ADHD, the GP appointment is the biggest obstacle. Not because GPs are unhelpful, but because ADHD is a condition that hides well — and a ten-minute appointment favours those who know how to present it." },
      { type: "heading", text: "Don't describe how you cope — describe what it costs" },
      { type: "paragraph", text: "The most common mistake people make is describing their compensatory strategies rather than their underlying difficulties. 'I make lots of lists' sounds organised. What the GP needs to hear is: 'Without lists I miss appointments, forget to pay bills, and have nearly lost jobs. Maintaining these systems takes so much energy that by the evening I'm completely depleted.'" },
      { type: "paragraph", text: "Describe the impact on real areas of your life: work, relationships, finances, sleep, self-esteem. Be specific about incidents, not just general tendencies." },
      { type: "pullquote", text: "The compensation is invisible to everyone but you. Your job in that appointment is to make it visible." },
      { type: "heading", text: "Mention that symptoms have been lifelong" },
      { type: "paragraph", text: "ADHD is a neurodevelopmental condition — by definition, its roots go back to childhood. Even if you weren't diagnosed then, and even if you coped reasonably well, tell your GP that these patterns have been present your whole life. This is clinically significant and distinguishes ADHD from conditions that develop in response to adult stress." },
      { type: "heading", text: "Bring something written" },
      { type: "paragraph", text: "A short written summary — even a page — of your key symptoms and their real-world impact is far more effective than trying to articulate everything in the moment. If you've completed the ADHD Mirror assessment, the GP export gives you a structured, clinically-framed summary you can hand over or read from directly." },
      { type: "heading", text: "Know your rights" },
      { type: "paragraph", text: "In England, the Right to Choose pathway means you can request a referral to any CQC-registered ADHD service, not just your local NHS provider. This can reduce waiting times significantly. You can mention this by name if your GP is unfamiliar with it." },
      { type: "heading", text: "If the first appointment doesn't go well" },
      { type: "paragraph", text: "You can request a second opinion, see a different GP at the same practice, or self-refer privately. A single appointment that doesn't result in a referral is not the end of the road. Many people with ADHD have to advocate persistently — which is, in itself, a particular kind of cruelty given that persistence and self-advocacy are among the things ADHD makes hardest." },
    ],
  },
  {
    id: "adhd-and-burnout",
    title: "ADHD and burnout: why they're so easily confused",
    subtitle: "Both leave you exhausted and unable to function. But the cause — and the recovery — are different.",
    readTime: "5 min read",
    description: "ADHD burnout and general burnout share many symptoms but have different roots. Understanding the difference matters for recovery and for knowing whether to seek an ADHD assessment.",
    content: [
      { type: "intro", text: "Burnout has become a widely recognised condition — the result of prolonged stress, overwork, or emotional depletion. ADHD burnout is something related but distinct: a collapse that happens when someone with ADHD has been masking, compensating, and pushing through for too long without the support they need." },
      { type: "heading", text: "What general burnout looks like" },
      { type: "paragraph", text: "General burnout typically develops in response to external circumstances — a demanding job, a difficult period, relentless pressure. The sufferer feels exhausted, cynical, and disconnected from work or life. Remove the stressor or allow sufficient rest, and recovery is usually possible." },
      { type: "heading", text: "What ADHD burnout looks like" },
      { type: "paragraph", text: "ADHD burnout often arrives after a prolonged period of successfully appearing to cope. The person has been running compensatory systems at maximum capacity — the lists, the early arrivals, the double-checking, the social performance. Then something tips the balance, and the systems collapse." },
      { type: "paragraph", text: "The result can look like a sudden, dramatic loss of function: inability to complete previously manageable tasks, emotional flooding, withdrawal, and a deep sense of shame. It often gets misread as depression." },
      { type: "pullquote", text: "ADHD burnout isn't about doing too much. It's about the hidden cost of doing ordinary things the hard way for too long." },
      { type: "heading", text: "Key differences" },
      { type: "paragraph", text: "In general burnout, rest is the primary treatment. In ADHD burnout, rest helps, but it doesn't address the underlying mechanism. If someone returns to the same environment — the same unaccommodated ADHD, the same compensatory effort — the cycle repeats." },
      { type: "paragraph", text: "The other distinguishing feature is history. ADHD burnout rarely appears from nowhere: there's usually a lifetime of effortful coping behind it. If you can trace your exhaustion back through years of always having to work harder than it seemed like you should have to, that pattern is worth exploring." },
      { type: "heading", text: "What to do if this sounds familiar" },
      { type: "paragraph", text: "If you recognise the ADHD burnout pattern, it's worth considering a formal assessment — not only to access treatment, but to understand what you've actually been carrying. Many people find that the diagnosis itself provides significant relief, because it reframes a lifetime of perceived personal failure as a neurological reality." },
    ],
  },
  {
    id: "inattentive-adhd",
    title: "Inattentive ADHD: the presentation that gets missed most",
    subtitle: "No hyperactivity, no obvious disruption — just a quiet, exhausting struggle to keep up.",
    readTime: "5 min read",
    description: "Inattentive ADHD doesn't look like the stereotype. It's internal, easy to miss, and disproportionately affects women. Learn what it actually looks like and why it goes undiagnosed.",
    content: [
      { type: "intro", text: "When most people picture ADHD, they imagine someone who can't sit still — fidgeting, interrupting, bouncing off walls. That picture describes one presentation of ADHD. The inattentive presentation looks almost nothing like it." },
      { type: "heading", text: "What inattentive ADHD actually looks like" },
      { type: "paragraph", text: "People with inattentive ADHD are often quietly struggling. They lose things constantly. They miss deadlines not from laziness but because time moves differently for them. They start things with genuine intention and can't finish them. They drift out of conversations, not rudely, just involuntarily." },
      { type: "paragraph", text: "They're often described as 'dreamy', 'ditzy', or 'not living up to their potential'. In school they may have been well-behaved and unremarkable — quietly not absorbing what was being taught, quietly exhausted by the effort of appearing present." },
      { type: "pullquote", text: "Inattentive ADHD is invisible precisely because the person is trying so hard not to let it show." },
      { type: "heading", text: "Why it disproportionately affects women" },
      { type: "paragraph", text: "Inattentive ADHD is more common in women and girls, though it affects people of all genders. Because it doesn't disrupt classrooms or create obvious behavioural problems, it rarely triggers the referrals that lead to diagnosis. Girls in particular are more likely to mask effectively, to internalise their struggles, and to be told that they're fine — even when they're not." },
      { type: "heading", text: "The emotional dimension" },
      { type: "paragraph", text: "Inattentive ADHD is frequently accompanied by significant emotional dysregulation that doesn't appear in the official diagnostic criteria but is widely recognised clinically. Rejection sensitivity — an intense, almost physical response to perceived criticism or failure — is particularly common and particularly poorly understood." },
      { type: "heading", text: "Getting a fair assessment" },
      { type: "paragraph", text: "Standard ADHD checklists, designed with hyperactive-impulsive presentations in mind, can significantly underestimate inattentive ADHD. If you're completing a self-assessment or seeking a formal evaluation, it's worth specifically discussing the inattentive presentation and its internal symptoms — not just the visible behaviours the original diagnostic tools were built to catch." },
    ],
  },
  {
    id: "adhd-and-sleep",
    title: "ADHD and sleep: why your brain won't switch off",
    subtitle: "Sleep problems in ADHD aren't a side issue — they're often central to the condition.",
    readTime: "4 min read",
    description: "Sleep problems are extremely common in adults with ADHD. Learn why ADHD makes it harder to fall asleep, stay asleep, and wake up — and what actually helps.",
    content: [
      { type: "intro", text: "Sleep problems are so common in adults with ADHD that some researchers consider them a core feature of the condition rather than a side effect. If you lie awake with a racing mind, struggle to wind down no matter how tired you are, or feel genuinely unable to wake up in the morning — this is likely not a discipline problem." },
      { type: "heading", text: "Why ADHD disrupts sleep" },
      { type: "paragraph", text: "Several mechanisms are at work. The ADHD brain is often under-aroused during the day, seeking stimulation to reach a functional baseline. At night, that same drive for stimulation makes it hard to disengage — the mind keeps generating new thoughts, plans, and anxieties to keep itself occupied." },
      { type: "paragraph", text: "There's also evidence that many people with ADHD have a delayed circadian rhythm, meaning their body clock is genuinely shifted later. They're not choosing to stay up late: their biology pushes them that way." },
      { type: "pullquote", text: "Telling someone with ADHD to 'just go to sleep earlier' is a bit like telling someone with poor eyesight to 'just look harder'." },
      { type: "heading", text: "The morning problem" },
      { type: "paragraph", text: "Waking up is often as difficult as falling asleep. Many adults with ADHD describe sleep inertia — a prolonged, intense grogginess that can last hours after waking. This isn't laziness. It reflects the same dysregulation that makes sleep initiation hard in the first place." },
      { type: "heading", text: "The anxiety-ADHD-sleep spiral" },
      { type: "paragraph", text: "Poor sleep worsens ADHD symptoms. Worse ADHD symptoms make sleep harder. Anxiety — which co-occurs with ADHD in roughly half of adults — adds another layer, making the mental chatter at bedtime more distressing. The spiral can be difficult to interrupt without addressing all three components." },
      { type: "heading", text: "What actually helps" },
      { type: "paragraph", text: "The evidence base points to consistent sleep and wake times (even when it feels impossible), reducing stimulation in the hour before bed, and addressing ADHD directly — because treated ADHD almost always improves sleep. Some people find that a short period of low-stimulation, low-demand activity (a familiar TV show, light reading) is more effective than trying to force stillness. Work with your neurology, not against it." },
    ],
  },
  {
    id: "adhd-and-emotional-dysregulation",
    title: "ADHD and emotional dysregulation",
    subtitle: "The symptom that barely appears in diagnostic criteria — but dominates daily life.",
    readTime: "5 min read",
    description: "Emotional dysregulation is one of the most impairing features of ADHD in adults, yet it's largely absent from diagnostic criteria. Learn what it looks like and why it matters.",
    content: [
      { type: "intro", text: "If you ask adults with ADHD what affects their life most, many won't say distraction or disorganisation. They'll describe the emotional side: the intensity, the volatility, the way a small frustration can feel catastrophic, the way perceived criticism can be physically painful." },
      { type: "heading", text: "Why emotional dysregulation isn't in the diagnostic criteria" },
      { type: "paragraph", text: "Emotional dysregulation was deliberately excluded from the DSM diagnostic criteria for ADHD in the 1990s, primarily to distinguish ADHD from mood disorders. The clinical consensus has shifted considerably since then — researchers like Russell Barkley have argued for decades that emotional dysregulation should be considered a core feature — but the diagnostic criteria haven't caught up." },
      { type: "paragraph", text: "This matters practically because many adults present to their GP with emotional symptoms and leave with a diagnosis of anxiety or depression, when the root cause is ADHD." },
      { type: "pullquote", text: "Emotions in ADHD aren't just felt more strongly — they arrive faster, are harder to modulate, and take longer to resolve." },
      { type: "heading", text: "Rejection sensitive dysphoria" },
      { type: "paragraph", text: "One of the most widely discussed features of ADHD emotional dysregulation is rejection sensitive dysphoria (RSD) — an intense, often overwhelming emotional response to perceived rejection, criticism, or failure. The key word is perceived: RSD can be triggered even when no rejection was intended." },
      { type: "paragraph", text: "People with RSD often describe it as one of the most impairing aspects of their ADHD — shaping careers, relationships, and self-worth in profound ways. It can manifest as avoiding any situation where failure is possible, people-pleasing to pre-empt rejection, or intense emotional reactions that seem disproportionate to observers." },
      { type: "heading", text: "Emotional dysregulation vs mood disorders" },
      { type: "paragraph", text: "A useful distinguishing feature is duration. In ADHD, emotional dysregulation tends to be intense but brief — the storm passes relatively quickly. In mood disorders, low mood or anxiety tends to be more sustained. If your emotional episodes are volcanic but short-lived, and have been your whole life, ADHD is worth exploring." },
      { type: "heading", text: "What this means for assessment" },
      { type: "paragraph", text: "When seeking an assessment or discussing symptoms with a GP, don't leave out the emotional dimension because it feels separate from 'real' ADHD symptoms. It isn't separate. Describe the intensity of your emotional responses, how quickly they arrive, how they've affected your relationships and work, and how long you've experienced them. It's part of the picture." },
    ],
  },
];
